// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMtPjPTMBHTRvqmqvknM4Z9hl-JTmbvyQ',
    appId: '1:59093251814:web:9fe112a9a33b72a920ed27',
    messagingSenderId: '59093251814',
    projectId: 'expense-manager-a7e2e',
    authDomain: 'expense-manager-a7e2e.firebaseapp.com',
    storageBucket: 'expense-manager-a7e2e.firebasestorage.app',
    measurementId: 'G-PXKFSG7VZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqXkFCIX0pnJRE_wtDG_FKKXpIVgnPd3A',
    appId: '1:59093251814:android:dccaea001b3c321a20ed27',
    messagingSenderId: '59093251814',
    projectId: 'expense-manager-a7e2e',
    storageBucket: 'expense-manager-a7e2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFsWOFW_6ywdM5BfcnmFpL81T-9uYOLbc',
    appId: '1:59093251814:ios:b77ccedcec08464720ed27',
    messagingSenderId: '59093251814',
    projectId: 'expense-manager-a7e2e',
    storageBucket: 'expense-manager-a7e2e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMadproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFsWOFW_6ywdM5BfcnmFpL81T-9uYOLbc',
    appId: '1:59093251814:ios:b77ccedcec08464720ed27',
    messagingSenderId: '59093251814',
    projectId: 'expense-manager-a7e2e',
    storageBucket: 'expense-manager-a7e2e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMadproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMtPjPTMBHTRvqmqvknM4Z9hl-JTmbvyQ',
    appId: '1:59093251814:web:89e592ea1a1564a220ed27',
    messagingSenderId: '59093251814',
    projectId: 'expense-manager-a7e2e',
    authDomain: 'expense-manager-a7e2e.firebaseapp.com',
    storageBucket: 'expense-manager-a7e2e.firebasestorage.app',
    measurementId: 'G-G537SZG3X0',
  );

}