// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqiT66MdUZA65HBnwZKNVbMkhx3FBZHZU',
    appId: '1:149480273715:web:1c8867ce334e3da920b046',
    messagingSenderId: '149480273715',
    projectId: 'ai-expense-manager-2de58',
    authDomain: 'ai-expense-manager-2de58.firebaseapp.com',
    storageBucket: 'ai-expense-manager-2de58.firebasestorage.app',
    measurementId: 'G-T7XQ7T9YJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALeHsxJ7Y0dVKap8IVZL4n7hK-Otmz5pU',
    appId: '1:149480273715:android:9ee36dec8e56090d20b046',
    messagingSenderId: '149480273715',
    projectId: 'ai-expense-manager-2de58',
    storageBucket: 'ai-expense-manager-2de58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBibMd_7qYlSLDQpw5t27_uZ9Sc4MFd_4Q',
    appId: '1:149480273715:ios:a55f27116ccf7ff320b046',
    messagingSenderId: '149480273715',
    projectId: 'ai-expense-manager-2de58',
    storageBucket: 'ai-expense-manager-2de58.firebasestorage.app',
    iosBundleId: 'com.ai.expensemanager.savings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBibMd_7qYlSLDQpw5t27_uZ9Sc4MFd_4Q',
    appId: '1:149480273715:ios:f5708e50c4f2cd5620b046',
    messagingSenderId: '149480273715',
    projectId: 'ai-expense-manager-2de58',
    storageBucket: 'ai-expense-manager-2de58.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMadproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqiT66MdUZA65HBnwZKNVbMkhx3FBZHZU',
    appId: '1:149480273715:web:072ac3d53ae6d00f20b046',
    messagingSenderId: '149480273715',
    projectId: 'ai-expense-manager-2de58',
    authDomain: 'ai-expense-manager-2de58.firebaseapp.com',
    storageBucket: 'ai-expense-manager-2de58.firebasestorage.app',
    measurementId: 'G-BJW57QCK15',
  );
}
