// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4VTD5kE_kN4KFLHF1FR1PlCNc5iSkvY',
    appId: '1:471280243926:web:b7d52abfa08a3604a86577',
    messagingSenderId: '471280243926',
    projectId: 'expenso-6b25c',
    authDomain: 'expenso-6b25c.firebaseapp.com',
    storageBucket: 'expenso-6b25c.firebasestorage.app',
    measurementId: 'G-JYQB11S1GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlm7iXzz03mmCeeD4oak4ueu2dD2m0Fg',
    appId: '1:471280243926:android:a45147c77e3fa901a86577',
    messagingSenderId: '471280243926',
    projectId: 'expenso-6b25c',
    storageBucket: 'expenso-6b25c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWivQd1F1ciJVUQXRDH3UOrgCzf1UNzss',
    appId: '1:471280243926:ios:139e9f40774581d1a86577',
    messagingSenderId: '471280243926',
    projectId: 'expenso-6b25c',
    storageBucket: 'expenso-6b25c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMadproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWivQd1F1ciJVUQXRDH3UOrgCzf1UNzss',
    appId: '1:471280243926:ios:139e9f40774581d1a86577',
    messagingSenderId: '471280243926',
    projectId: 'expenso-6b25c',
    storageBucket: 'expenso-6b25c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationMadproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg4VTD5kE_kN4KFLHF1FR1PlCNc5iSkvY',
    appId: '1:471280243926:web:f6fb20c79dec87d3a86577',
    messagingSenderId: '471280243926',
    projectId: 'expenso-6b25c',
    authDomain: 'expenso-6b25c.firebaseapp.com',
    storageBucket: 'expenso-6b25c.firebasestorage.app',
    measurementId: 'G-2BQLR4MJ7Y',
  );

}